### PR TITLE
typos

### PR DESCRIPTION
**Pull request by Adafede**
@mmzdouc 😝

### CODE REVIEW

**Comment by Adafede** [comment]
By the way, when running the tests using `dev:pytest` it looks like my hatch does not find `mite_extras`... not used to hatch so probably I did something wrong?

**Comment by Adafede** [comment]
> By the way, when running the tests using `dev:pytest` it looks like my hatch does not find `mite_extras`... not used to hatch so probably I did something wrong?

Ok, one has to not only remove the env but also dev, everything works!

**Comment by mmzdouc** [comment]
Ups, thanks for picking up the typo!

**Review by mmzdouc — APPROVED** [review]
LGTM

**Pull request merged**
